export const stations = [
  "NDLS - New Delhi",
  "CSMT - Mumbai CSMT",
  "HWH - Howrah Jn",
  "MAS - Chennai Central",
  "SBC - KSR Bengaluru",
  "YPR - Yesvantpur Jn",
  "SUR - Solapur Jn",
  "PNBE - Patna Jn",
  "LKO - Lucknow NR",
  "CNB - Kanpur Central",
  "ALD - Prayagraj Jn",
  "BSB - Varanasi Jn",
  "GKP - Gorakhpur Jn",
  "JP - Jaipur Jn",
  "ADI - Ahmedabad Jn",
  "ST - Surat",
  "BRC - Vadodara Jn",
  "PUNE - Pune Jn",
  "NGP - Nagpur",
  "BPL - Bhopal Jn",
  "INDB - Indore Jn",
  "BBS - Bhubaneswar",
  "SEC - Secunderabad Jn",
  "HYB - Hyderabad Deccan",
  "VSKP - Visakhapatnam",
  "BZA - Vijayawada Jn",
  "TVC - Thiruvananthapuram Central",
  "ERS - Ernakulam Jn",
  "CDG - Chandigarh",
  "ASR - Amritsar Jn",
  "GHY - Guwahati",
  "TATA - Tatanagar Jn",
  "RNC - Ranchi",
  "R - Raipur Jn",
  "DDU - Pt. DD Upadhyaya Jn",
  "MDU - Madurai Jn",
  "CBE - Coimbatore Jn",
  "TBM - Tambaram",
  "MS - Chennai Egmore",
  "LTT - Lokmanya Tilak Terminus",
  "BVI - Borivali",
  "SDAH - Sealdah",
  "KGP - Kharagpur Jn"
];

export const airports = [
  "DEL - Indira Gandhi Intl (New Delhi)",
  "BOM - Chhatrapati Shivaji Maharaj Intl (Mumbai)",
  "BLR - Kempegowda Intl (Bengaluru)",
  "HYD - Rajiv Gandhi Intl (Hyderabad)",
  "MAA - Chennai Intl",
  "CCU - Netaji Subhash Chandra Bose Intl (Kolkata)",
  "AMD - Sardar Vallabhbhai Patel Intl (Ahmedabad)",
  "COK - Cochin Intl",
  "PNQ - Pune Intl",
  "GOI - Dabolim (Goa)",
  "GOX - Manohar Intl (Goa)",
  "LKO - Chaudhary Charan Singh Intl (Lucknow)",
  "GAU - Lokpriya Gopinath Bordoloi Intl (Guwahati)",
  "TRV - Trivandrum Intl",
  "JAI - Jaipur Intl",
  "BBI - Biju Patnaik Intl (Bhubaneswar)",
  "PAT - Jay Prakash Narayan Intl (Patna)",
  "IXC - Chandigarh Intl",
  "ATQ - Sri Guru Ram Dass Jee Intl (Amritsar)",
  "VNS - Lal Bahadur Shastri Intl (Varanasi)"
];

export const cities = [
  "Mumbai, Maharashtra",
  "Delhi, NCR",
  "Bengaluru, Karnataka",
  "Hyderabad, Telangana",
  "Ahmedabad, Gujarat",
  "Chennai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Surat, Gujarat",
  "Pune, Maharashtra",
  "Jaipur, Rajasthan",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Indore, Madhya Pradesh",
  "Thane, Maharashtra",
  "Bhopal, Madhya Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Pimpri-Chinchwad, Maharashtra",
  "Patna, Bihar",
  "Vadodara, Gujarat",
  "Ghaziabad, Uttar Pradesh",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Faridabad, Haryana",
  "Meerut, Uttar Pradesh",
  "Rajkot, Gujarat",
  "Kalyan-Dombivli, Maharashtra",
  "Vasai-Virar, Maharashtra",
  "Varanasi, Uttar Pradesh",
  "Srinagar, Jammu & Kashmir",
  "Aurangabad, Maharashtra",
  "Dhanbad, Jharkhand",
  "Amritsar, Punjab",
  "Navi Mumbai, Maharashtra",
  "Allahabad, Uttar Pradesh",
  "Ranchi, Jharkhand",
  "Howrah, West Bengal",
  "Coimbatore, Tamil Nadu",
  "Jabalpur, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Jodhpur, Rajasthan",
  "Madurai, Tamil Nadu",
  "Raipur, Chhattisgarh",
  "Kota, Rajasthan",
  "Guwahati, Assam",
  "Chandigarh",
  "Solapur, Maharashtra"
];

export const busStands = [
  "ISBT Kashmiri Gate - Delhi",
  "Kempegowda Bus Station (Majestic) - Bengaluru",
  "Koyambedu Bus Terminus (CMBT) - Chennai",
  "Swargate Bus Stand - Pune",
  "Geeta Mandir Bus Stand - Ahmedabad",
  "Mahatma Gandhi Bus Station - Hyderabad",
  "Anand Vihar ISBT - Delhi",
  "Shivajinagar Bus Station - Pune",
  "Arapalayam Bus Stand - Madurai",
  "Alambagh Bus Stand - Lucknow"
];

export const hillStations = [
  "SML - Shimla (KSR)",
  "KLK - Kalka (KSR)",
  "DJ - Darjeeling (DHR)",
  "NJP - New Jalpaiguri (DHR)",
  "UAM - Udagamandalam (NMR)",
  "MTP - Mettupalayam (NMR)",
  "NRL - Neral (Matheran)",
  "MAE - Matheran",
  "PTK - Pathankot (KVR)",
  "JDNX - Joginder Nagar (KVR)"
];

export const touristStations = [
  "DSJ - Delhi Safdarjung (Maharaja)",
  "JP - Jaipur Jn (Palace on Wheels)",
  "CSMT - Mumbai CSMT (Deccan Odyssey)",
  "YPR - Yesvantpur (Golden Chariot)",
  "AGC - Agra Cantt",
  "BSB - Varanasi Jn",
  "UDA - Udaipur City",
  "JSM - Jaisalmer",
  "HWH - Howrah (Buddhist Circuit)",
  "GAYA - Gaya Jn"
];
